### PR TITLE
Tokenizer introduced 

### PR DESCRIPTION
**Pull request by niebert**
Hi Spencer, introduced the tokenizer for Math and References, with the current version I do not populate `doc.references` instead `doc.refs4token` so you have both the standard parsing of references in `doc.references` and parsing of refs `doc.refs4token`, which needs to have more attributes, especially `label` for backward replacement of tokens like `___CITE_7238234792_Miller_Eric_2012___`  into `(Miller 2012)` or `[9]`.

You can check the tokenizer with `bin/wtf4file.js` and the tokenizer itself is available `src/01-document/preProcess/tokenize.js`.  The Tokenizer is called in `src/01-document/preProcess/index.js`.  

> I'm thinking of things like, references inside a table. We replace our reference with a timestamp, but then the table parser removes that whole `{| ... |}` section, so afterwards, when we go to reconcile it, we can't find our timestamp anymore.
>> Yes, you are right, that the table parser removes `{| ... table cell content ___CITE_7238234792_Miller_Eric_2012___ more  table cell content ... |}`  but the cell content is not lost, because it is stored in JSON so you will find the cell content 

`... table cell content ___CITE_7238234792_Miller_Eric_2012___ more  table cell content ...` 

in the table object in `doc`.  Rendering the output in:
* MarkDown,
* LaTeX,
* HTML,
* JSON,

replacement of the citation in table can be done after the final HTML, LaTeX, Markdown is generated. You will find the marker `___CITE_7238234792_Miller_Eric_2012___` e.g. in the generated HTML in the appropriate table cell, because table parser extracts the cell content and this includes the string `___CITE_7238234792_Miller_Eric_2012___`. 

Furthermore if you want to preserve the position of the table, leave a token behind  after removal of `{| ... |}` section e.g. `___TABLE_7238234792_T1___` and store the table token `___TABLE_7238234792_T1___` as label in the JSON for replacement of generated table at position where it was removed by the parser. 
 
> Right now the wikitext string is getting smaller-and-smaller during the parsing process, 

The tokenizer shrinks also the wikitext but the only difference is that the tokenizer leaves marker behind that shifts the ToDo of marker replacement to the output generation. If you generated the table with tokenized content the marker `___CITE_7238234792_Miller_Eric_2012___` appears in the appropriate table cell, when you call the table generator e.g for Markdown with `toMarkdown()` call.
This implies, that we'd need to replace the label `___CITE_7238234792_Miller_Eric_2012___` even in the JSON, if you call the output for JSON with `toJSON()`.  You cannot replace the marker before, because the references must be handled according to the output format. E.g. in `toLatex()` call the citation will be replaced the marker with `\cite{Miller_Eric_2012}` and in the plain text with `(Miller 2012)`. The tokenizer creates just labels like `___CITE_7238234792_Miller_Eric_2012___` as text and if the parser does not remove text in the table nothing is lost even if you remove `{| ... |}` completely without a table-marker. Even if you loose the table position by not setting a token `___TABLE_7238234792_T1___`  for the table `T1`, the label `___CITE_7238234792_Miller_Eric_2012___` will appear when you generate the tables in the output.

If I am wrong, please correct me, Spencer
best regards, Bert

### CODE REVIEW

**Comment by spencermountain** [comment]
hey @niebert looks like you'll need to rebase to the latest version of master. There's [no real easy](https://stackoverflow.com/questions/3876977/update-git-branches-from-master) way to do that, but that's a 164-file diff!

**Comment by spencermountain** [comment]
yeah, supporting `(Miller 2012)` and stuff is a really neat idea!

Let's focus on replacing the <ref> with the `___CITE...___`, then making sure we remove them from the string. I'm concerned about this a little bit, we had `.wikitext()` on every class, then we were manipulating the string,  in different places and even that got complicated.

Let's do this in small bits? Happy to help.

**Comment by spencermountain** [comment]
I'm thinking of things like, references inside a table. We replace our reference with a timestamp, but then the table parser removes that whole `{| ... |}` section, so afterwards, when we go to reconcile it, we can't find our timestamp anymore.

Right now the wikitext string is getting smaller-and-smaller during the parsing process, so we'd need to start thinking about it somehow as a source-of-truth.

Open to suggestions or PRs, thinking about it aloud. what do you think?

**Comment by spencermountain** [comment]
Sorry, last thought:

It would be amazing if we could eventually reconcile references at the sentence-level. 

If you think about the big-insane wikitext string, getting cleaner and cleaner as it gets parsed, eventually we have something that is *only* sentence-text. That's our tacit assumption, at least.

Never really thought about it that way.

If we had references in Sentences, Tables, Infoboxes, etc - all of them would need to pull-out the `___CITE...` text themselves, then store the reference themselves, so `Document.references()` would be like:
```js
sentences().references() + tables.references() + lists.references() ....
```
finding them placed in all the specific objects.

🤔

**Comment by niebert** [comment]
Hi Spencer,
excuse me for version conflict. Just use  the tokenizer `src/01-document/preProcess/tokenize.js` and the  call of Tokenizer is called in `src/01-document/preProcess/index.js`.  Anything else should be used from the current `wtf_wikipedia` version.  Calling the tokenizer is shown in  `bin/wtf4file.js` in [bin/wtf4file.js](https://www.github.com/niebert/wtf_wikipedia/blob/master/bin/wtf4file.js) and the tokenizer itself is availableThe main tokenizer is just
just use the `src/01-document/preProcess/tokenizer.js` 
```javascript
 options = {
      "tokenize":{
        "math": true,
        "citation": true
      }
    };
console.log(wtf(data,options).html());
```

**Comment by spencermountain** [comment]
okay, cool. i'll take a look at it this week.

**Comment by niebert** [comment]
The tokenizer was called in preprocess on the full wiki, so all ref-tags will be replaces and store in `data.token4refs

> Sorry, last thought:
> 
> It would be amazing if we could eventually reconcile references at the sentence-level.
> 
> If you think about the big-insane wikitext string, getting cleaner and cleaner as it gets parsed, eventually we have something that is _only_ sentence-text. That's our tacit assumption, at least.
> 
> Never really thought about it that way.
> 
> If we had references in Sentences, Tables, Infoboxes, etc - all of them would need to pull-out the `___CITE...` text themselves, then store the reference themselves, so `Document.references()` would be like:
> 
> ```js
> sentences().references() + tables.references() + lists.references() ....
> ```
> 
> finding them placed in all the specific objects.

Tokenizer extracts all references in the preprocess of the complete wiki text and stores the references in the `Document`. If you call the tokenizer now, on section, paragraph, table or sentence level there won't be any references that can be parsed anymore. Only markers are there, that are handled as ordinary text. best regards, Bert

**Comment by niebert** [comment]
Hi Spencer, 
I did the following changes to your current repo for introduction of Tokenizer:
introduced the tokenizer as lib in `src/01-document/preProcess/tokenizer.js`
embedded into parsing process in `src/01-document/preProcess/index.js`

**Comment by spencermountain** [comment]
hey Engelbert, i've just released support for a bunch (+20%?) of new templates, including xml-variants of both math and chem templates in `6.3.0`. 

...it's a bit of a mess still, but continuing to improve.

**Comment by spencermountain** [comment]
i guess what i mean is, being able to inline-replace templates like this is getting closer, but maybe a little early yet.

what do you think about [this output?](https://runkit.com/spencermountain/5beed1892d7751001321b035)

**Comment by spencermountain** [comment]
gonna close this, as it's a few releases behind. we've added support for the math templates since November.
I'll keep it bookmarked for your implementation of backward replacement for references, which is doable early in the new year.

**Comment by niebert** [comment]
Cool thank you very much, sorry for being late to repond.
I noticed that the math expression appear in the generated JSON. This is fantastic.
Have a wonderful Christmas time and a happy new year.
Thank you for all your developments and progress of `wtf_wikipedia`. I appreciate that very much,
Bert

**Pull request closed without merging**
