### PR TITLE
Chage Section to use class

### PR DESCRIPTION
**Pull request by wvanderp**
hello,

the first part of PR is the result of some procrasti-working (procrastination and working) and the second part is doing the same to section as I did to document

**worked on the fetch lib**
added jsdocs 
simplified the overloads
documented some of the options in jsdoc types

**added some more typescript infrastructure**
because typescript, type generation, auto complete, vs code and jsdoc are very closely related i thought it would be handy to have maybe some more typescript stuff

This commit adds `tsconfig.json` which controls how typescript works on this repo. currently i have it configured as a type checking tool for the js files.

I also added a config for type generation this bings it one step closer to replacing the static types.

this is one of my more controversial commits so i'm happy to remove it if you ask so

**cleaned template parsing somewhat and split out some helper functions**
more jsdocs, eslint fixes and dry programming 

**refactored Sections to es classes**
adding more tests for section
refactoring the section class 
fixing the test afterwards

This PR is not done jet I still need to add jsdoc to the sections class

-wvanderp

### CODE REVIEW

**Comment by wvanderp** [comment]
I have the sneaking suspicion that altough we have 87% test coverage that we dont test all the code in a good way.

because i only found the depth bugs because I saw that the test coverage droped

**Comment by spencermountain** [comment]
looks great so far! thank you for adding tests, and working through the weird method overloading in fetch.
You're welcome to add any checks and scripts for making the typescript part of the project smarter. 
Things change a fair amount, and right now there's no way of saying 'hey typescript, things still cool?'
Let me know when you're ready.
cheers

**Comment by wvanderp** [comment]
I was looking at `nextSibling` and `lastSibling` (which i interpreted as `previous sibling`) https://github.com/spencermountain/wtf_wikipedia/blob/805d725abf4ec0574616356daea5e762f2dcf347/src/02-section/Section.js#L182-L205

and I was wondering why the `next sibling` has a lot of logic and the `previous sibling` just says the previous in the list, does not matter that is not a sibling.

and then the `children` function continues with the logic.

Why is `lastSibling` different? Should we edit it to use the correct behaviour?

**Comment by spencermountain** [comment]
@wvanderp good point. you're right. `prevSibling()` should be sensitive to depth, like `nextSibling` is.

my thinking (in like 2010) was this:
```
==One==
===One a===
===One b===
==Two==
```
`nextSibling` of `One` should be `Two`, not `One a`.
i suppose `prevSibling` of `Two` should be `One`!

🏅 you are a very good software developer. I never noticed this. 🏅

**Comment by spencermountain** [comment]
gonna play-around with a new plugin, so will merge this into dev to avoid a merge-conflict.
Will wait until you're ready for a new release.
cheers

**Comment by spencermountain** [comment]
just playing-around with a new plugin on dev - i disabled the jsdoc and comment lint rules temporarily, so there was less red-lines, but feel-free to turn them back on. If you need help updating your branch, lemme know.

**Comment by spencermountain** [comment]
hah, sorry - i've gotten triggered and have started adding jsdoc annotations everywhere. These are like bubble-wrap.
You'll have to git pull @wvanderp.

**Pull request merged**
