### PR TITLE
add Coor template

### PR DESCRIPTION
**Pull request by wvanderp**
this pull request will implement parsing:
[Coor title dms](https://nl.wikipedia.org/wiki/Sjabloon:Coor_title_dms)
[Coor title dec](https://nl.wikipedia.org/wiki/Sjabloon:Coor_title_dec)
[Coor dec](https://nl.wikipedia.org/wiki/Sjabloon:Coor_dms)
[Coor dm](https://nl.wikipedia.org/wiki/Sjabloon:Coor_dm)
[Coor dec](https://nl.wikipedia.org/wiki/Sjabloon:Coor_dec)

### CODE REVIEW

**Comment by spencermountain** [comment]
thanks @wvanderp

**Comment by spencermountain** [comment]
hey @wvanderp is there any way to consolidate `coord` and `coor`?
i'm trying to re-use the parsing template code for both, and don't know what i'm doing.
thanks!

**Comment by wvanderp** [comment]
I think we can consolidate the code into one file.

But I think there is an other problem. I think that we should return the right name of the template. 

#200 tried to fix that but it still needs a fix along the way I think I have some time to fix that and shall add it to #200

**Comment by spencermountain** [comment]
awesome, thank you.

**Pull request merged**
