### PR TITLE
Added reveal() export formats to AST nodes of wtf_wikipedia

### PR DESCRIPTION
**Pull request by niebert**
according to the tests with [https://niebert.github.io/Wiki2Reveal/ Wiki2Reveal] I added the reveal() method to the tree nodes of the Abstract Syntax Tree generated with `wtf_wikipedia`.  Hope that added feature is ok for you. Tried to reuse most of the html export function and added the `toReveal.js` according to your software design. Thank you for all your improvements during the last year, Spencer - well done

### CODE REVIEW

**Comment by spencermountain** [comment]
hey @niebert just got a chance to play with wiki2reveal. Cool stuff!
Yeah, i've been stuck on [another library](https://github.com/spencermountain/compromise/tree/linked-list) for the past few months. Will finish that in december, then begin work on supporting the work you've been doing in january. 

it looks like there's a merge conflict on this branch, it may need some work in order to merge them.

If I can remember, our plan was to export the raw `Doc`, `Table` etc classes in an extend method, so that we can do proper plugins. That way, we can convert html, latex, markdown, and wiki2reveal to seperate plugins, to keep filesize small. 
There was also the plan to roll `.templates()` into a class structure, like the others.
Anyways, i know it's been a few weeks but v8 will get done in the new year.  It may be best to wait for that.
Lemme know what you think.
cheers

**Comment by niebert** [comment]
no worries spencer, you integrated most of it already.

* **Step 1:** `wtf_fetch()` based on `cross-fetch` fetches the wiki source
** **Input:** 
*** `language="en"` or `language="de"` to specify the language of the wiki source
*** `domain="wikipedia"` or `domain="wikiversity"` or `domain="wikispecies"` to select the wiki domain the `wtf_fetch` pulls the wiki source from
** **Output:**
*** wiki source text e.g. from `wikipedia` or `wikiversity`
** Remark: `wtf_fetch` extracts your `wtf.fetch()` in a separate module. 
* **Step 2:** `wtf_tokenize()` 
** **Input:** 
*** wiki source text e.g. from `wikipedia` or `wikiversity` fetched by `wtf_fetch`
** **Output:**
*** wiki source text where e.g. mathematical expressions are replaced by tokens like `MATH-INLINE-839832492834_N12`. `wtf_wikipedia` treats those tokens just as words in a sentence. Then tokens appear in the output from `wtf_wikipedia.doc. html()` or `wtf_wikipedia.doc.latex()`. From that status you `detokenize.html` the output according to desired format  e.g. for latex the detokenizer replaces the word/token `MATH-INLINE-839832492834_N12` by `$\sum_{n=0}^{\infty} \frac{x^n}{n!}$`. The only thing I guess would be helpful is that the constructors for the AST treenode e.g. `Reference`, `MathFormula`, .... should be extendable with additional export formats e.g. `doc.reveal()` that visits the AST tree nodes `Section`, `Paragraph`, `Sentence`, ....  and calls the appropriate `toReveal()` function for the node.
Might be sufficient to add it the following way:
```javascsript 
Document.reveal = function () {
   ....
};

Document.Section.reveal = function () {
   ....
};

Document.Section.Paragraph.reveal = function () {
   ....
};
...
```
`Section` might own different constructors for tree nodes of the AST (Abstract Syntax Tree), so 
```javascsript 
Document.Section.Table.reveal = function () {
   ....
};
```
resp. assigned to paragraph level.
```javascsript 
Document.Section.Paragraph.Table.reveal = function () {
   ....
};
```

**Comment by niebert** [comment]
Hi Spencer, compromise is really amazing. NLP could be helpful in so many applications, e.g.:
* for speech recognition, n-gram recognition in wikipedia text examples, imagine to populate `wtf_fetch` sources from wikipedia, extract the plain text from wikipedia, assign the grammar preprocessing to the AST. If I had time, I would like to combine [pocketsphinx](https://github.com/syl22-00/pocketsphinx.js) with comprise in javascript tool chain 
* futhermore compromise would be helpful for web based translation - e.g. train a fast neural machine translation like https://marian-nmt.github.io/ and create small domain specific subset for translation of specific textfragments with NPM and Javascript.

**Comment by spencermountain** [comment]
hey, I went ahead and created this `.extend()` method that we discussed before.
if you update to `7.8.0`, you'll be able to do this:

```js
wtf.extend(models => {
  // add a method to the Doc class
  models.Doc.prototype.sayHi = function() {
    console.log('hello ' + this.title())
  }
})

wtf.fetch('Miami', 'en', function(err, doc) {
  doc.sayHi()
})
```

as you [can see](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/index.js#L8), any classes can be directly updated now, without any weird stuff.

lemme know!

**Comment by niebert** [comment]
Well done, Spence, Thank you very much.

**Pull request closed without merging**
