### PR TITLE
fix for special namespaces like "cookbook" which get their their text dumped for looking like interwiki links

### PR DESCRIPTION
**Pull request by ephdot**
This should pass the test, but keeps extra text in cases where the link is not interlanguage.

If this makes the text too verbose, we can add an option such as verbose to toggle it?

Needed for cases where the name-space is cookbook or wikijunior.

### CODE REVIEW

**Comment by ephdot** [comment]
Argh!!  This doesn't work with wikijunior.  The main page doesn't follow the namespace:title convention.  Also, didn't realize that personal repository changes were reflected in the pull request.  What a mess...  Sorry about this.

**Comment by spencermountain** [comment]
ha! if you think that's a mess, you should see some other prs i've gotten. 
lemme know if i can help
cheers!

**Comment by ephdot** [comment]
I'm testing out the verbose idea - best of the bad options...   If it works, I'll reopen the pull request.

**Comment by ephdot** [comment]
So, I added a namespace option which can be set to "cookbook" or "wikijunior" for example so that the namespace doesn't get dumped from the text.

**Comment by spencermountain** [comment]
thanks!

**Pull request merged**
