### PR TITLE
Feature/append section labels with parent

### PR DESCRIPTION
**Pull request by moustachedelait**
Hi Spencer, this PR is totally optional, and only wanted to offer it because I like your project. For my own project, I needed the keys to have the parent names in them. An image explains it better than any words could: 
parentnodes 

So my PR adds an option (which by default is off, so no-one should see a difference unless they start adding that option) that does that. If you think it's not useful, or ugly code, don't hesitate to reject and ill just keep it in my fork.

Thanks!
-Guido

### CODE REVIEW

**Comment by spencermountain** [comment]
oh neat, hi Guido.
i like that.
wanna call it `flatten`? or something like that?
happy to merge it

**Comment by spencermountain** [comment]
i guess we already store it flat, don't we. Maybe we should represent the tree-structure better, so this sort of thing is easier to do.

man, this project needs a lot of work, doesn't it. Thanks for giving it a nudge or two.
wanna change the return-format somehow? i trust you can figure-out something cool
:peace_symbol:

**Comment by moustachedelait** [comment]
Yeah a JSON object with title, text and children would perhaps be the most natural. That'll take me a while to get to though. I'll decline this PR for now.

**Comment by spencermountain** [comment]
too late!
bwah ha ha! :japanese_ogre:

**Comment by spencermountain** [comment]
lemme know if i can help at all

**Comment by chocomega** [comment]
Yes please, a tree representation would be nice !
It's a pain in the *ss to find a parser that fits my need and this one seems to be a really good candidate :)
Thanks

**Comment by spencermountain** [comment]
started on this today, will have something hopefully later this afternoon

**Comment by spencermountain** [comment]
hey, this is now a flat array, but each heading has a depth integer, so calculating `appendSectionLabel` post-hoc, and whatever else, is much easier.
`v1.0.0` :guitar:

**Pull request merged**
