### PR TITLE
Update doc.js

### PR DESCRIPTION
**Pull request by wvanderp**
hello,

this PR is essecialy the same as https://github.com/spencermountain/wtf_wikipedia/pull/398 . diffrence being that this only includes eslint fixes for the changed files.

It is how ever dependant on https://github.com/spencermountain/wtf_wikipedia/pull/399 becouse it is based on my master branch.

-wvanderp

### CODE REVIEW

**Comment by spencermountain** [comment]
k, I'll take a look with some fresh-eyes tomorrow.
thanks!

**Comment by spencermountain** [comment]
this is so great.

**Comment by spencermountain** [comment]
ah cool, vscode handles jsdoc just like that. No config needed. That is pretty helpful!

do you use `prettier`? I'm getting a space after function, before the parenthesis. Does that happen for you too?

Our node_modules is now nearly 400mb - I know it's hacky, but is there a smart way to install things only as we need them in the github actions? The `tsd-jsdoc` one installs all of typescript, for example. Not a huge deal, just curious.

**Comment by wvanderp** [comment]
**Software being cool**

> ah cool, vscode handles jsdoc just like that. No config needed. That is pretty helpful! 

yes, in webstorm it even uses it for some basic type checking. it also appears that vs code takes some clues from the eslintrc for code styling.

**eslint rules**

> do you use prettier? I'm getting a space after function, before the parenthesis. Does that happen for you too?

It's a eslint rule. I was looking at what the most common use os spaces was. and it was a space after the function name

https://github.com/spencermountain/wtf_wikipedia/blob/af9047f875d0d02b4754d452bc98ad64d9f38653/.eslintrc#L54-L60
this is the rule that defines that behavior.

I let webstorm infer the code style from the eslint file and eslint also checks for style errors.

**node_modules: an absolute unit**

> Our node_modules is now nearly 400mb - I know it's hacky, but is there a smart way to install things only as we need them in the github actions? The tsd-jsdoc one installs all of typescript, for example. Not a huge deal, just curious.

I like the dev environment and the built environment to be kind of the same so that I can do everything I want to do without remembering that i need to install a package locally for that. that's why I add everything to the devdependencies.

for me it is already over 400mb with 280 in the main repo and then 9*20 = 200mb in all the plugin folders

I tried https://github.com/ModClean/modclean . but it didn't help much it only removed 20mb of stuff on its hardest setting and then the project was broken. 

what mabey could help is reusing roll up from the main folder for the plugins because right now we have 200mb of duplicate stuff.

I'll look further into size reduction when i look at type generation.

**hacktoberfest **

lastly I have to ask a small favor. I started this project to participate in hacktoberfest and chose wtf-wikipedia because i like to use it and want to make it better. as you might know hacktoberfest changed its rules for counting of PRs ( see: https://hacktoberfest.digitalocean.com/hacktoberfest-update).

I'd like to get this commit to be counted for my hacktoberfest. could you label the project with a `hacktoberfest-accepted` label till the end of oktober when the PRs are counted?

**Comment by spencermountain** [comment]
sure! added the label to the repo.

yeah, that must have changed in prettier at some point. I'll do whatever.

as you've seen, a lot of the tests still use var, I don't remember why. I don't mind doing a search/replace, or if you've got a clever script, fire away!
thanks for your help.

**Comment by wvanderp** [comment]
Adding the tag didn't work correctly.

Its either `hacktoberfest-accepted` to the PR or `hacktoberfest` to the repo

congratulation btw on you 400th pull request

**Pull request merged**
